SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS PLAYERS;

CREATE TABLE PLAYERS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  LOGIN VARCHAR(128) NOT NULL,
  PASSWORD VARCHAR(128) DEFAULT NULL,
  EMAIL VARCHAR(128) DEFAULT NULL,

  PRIMARY KEY (ID),
  CONSTRAINT UC_PLAYER UNIQUE (LOGIN)
)
ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET = UTF8;

INSERT INTO PLAYERS (ID, LOGIN, PASSWORD, EMAIL) VALUES (1, 'ANONYMOUS', NULL, NULL);

DROP TABLE IF EXISTS GAMES;

CREATE TABLE GAMES (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(128) NOT NULL,
  PASSWORD VARCHAR(128) DEFAULT NULL,
  PLAYER_BLACK INTEGER NOT NULL DEFAULT 1,
  PLAYER_WHITE INTEGER NOT NULL DEFAULT 1,
  STATE VARCHAR(1024) DEFAULT NULL,
  START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (ID),

  CONSTRAINT FK_PLAYER_BK_IDX FOREIGN KEY (PLAYER_BLACK) 
  REFERENCES PLAYERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,

  CONSTRAINT FK_PLAYER_WH_IDX FOREIGN KEY (PLAYER_WHITE) 
  REFERENCES PLAYERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  
  CONSTRAINT UC_GAME UNIQUE (NAME)
) 
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

SET FOREIGN_KEY_CHECKS = 1;