USE heroku_eea3932bd3d56f0;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS PLAYERS;

CREATE TABLE PLAYERS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  LOGIN VARCHAR(128) NOT NULL,
  PASSWORD VARCHAR(128) DEFAULT NULL,
  EMAIL VARCHAR(128) DEFAULT NULL,

  PRIMARY KEY (ID),
  CONSTRAINT UC_PLAYER UNIQUE (LOGIN)
)
ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET = UTF8;

INSERT INTO PLAYERS (LOGIN, PASSWORD, EMAIL) VALUES ('ANONYMOUS', NULL, NULL);

DROP TABLE IF EXISTS GAMES;

CREATE TABLE GAMES (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(128) NOT NULL,
  PASSWORD VARCHAR(128) DEFAULT NULL,
  PLAYER_BLACK INTEGER DEFAULT 1,
  PLAYER_WHITE INTEGER DEFAULT 1,
  STATE VARCHAR(1024) DEFAULT NULL,
  START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (ID),
  KEY FK_PLAYER_BK_IDX (PLAYER_BLACK),
  KEY FK_PLAYER_WH_IDX (PLAYER_WHITE),

  CONSTRAINT FK_PLAYER_BK_IDX FOREIGN KEY (PLAYER_BLACK) 
  REFERENCES PLAYERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,

  CONSTRAINT FK_PLAYER_WH_IDX FOREIGN KEY (PLAYER_WHITE) 
  REFERENCES PLAYERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) 
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

SET FOREIGN_KEY_CHECKS = 1;
